### ISSUE TITLE
Add bevy_fluent to perhaps a Localization category 

### ISSUE THREAD

**Issue by TheLeonsver1** [bevyengine/awesome-bevy#96]
This is an issue and not a pr because I don't know whether to create a new category(i think we should) and where to place such category in relation to the others, my guess would be near development tools.
`bevy_fluent` is located here: https://github.com/kgv/bevy_fluent

**Comment by cart** [comment]
I think translations probably fall nicely into an "Accessibility" category?

**Comment by TheLeonsver1** [comment]
I've asked the community for input and they agree about "Accessibility", where would you want to put it in relation to other categories if that matters at all?

**Comment by cart** [comment]
Somewhere near the top. In the near-ish future we'll be moving to a webpage based awesome-bevy solution, so the current ordering doesn't matter much.

**Comment by TheLeonsver1** [comment]
I'll wait a bit to see if the author is still active on github. He has last updated the crate in march and it's not updated to 0.5 yet so I'm a little hesitant about adding it at the moment.
